defmodule BSV.Contract.P2STAS do
  @moduledoc """
  Pay to S.T.A.S. contract.

  P2STAS scripts are used to lock Bitcoin as a STAS token to an [`address`](`t:BSV.Address.t/0`).
  The Bitcoin can later be unlocked using the private key corresponding to the
  address.

  STAS imposes some restrictions on what is spendable, namely by default, for NFTs the tokens cannot be split, so that
  number of satoshis minted into a STAS token cannot be separated unless it is redeemed to a redemption address

  ## Lock parameters

  * `:address` - A `t:BSV.Address.t/0` struct.

  ## Unlock parameters

  * `:keypair` - A `t:BSV.KeyPair.t/0` struct.

  ## Examples

      iex> contract = P2STAS.lock(1, %{address: Address.from_pubkey(@keypair.pubkey)})
      iex> Contract.to_script(contract)
      %Script{chunks: [
        :OP_DUP,
        :OP_HASH160,
        <<83, 143, 209, 121, 200, 190, 15, 40, 156, 115, 14, 51, 181, 246, 163, 84, 27, 233, 102, 143>>,
        :OP_EQUALVERIFY,
        :OP_CHECKSIG,
        ...
      ]}

      iex> contract = P2PKH.unlock(%UTXO{}, %{keypair: @keypair})
      iex> Contract.to_script(contract)
      %Script{chunks: [
        <<0::568>>, # signatures are zero'd out until the transaction context is attached
        <<3, 248, 31, 140, 139, 144, 245, 236, 6, 238, 66, 69, 234, 177, 102, 232, 175, 144, 63, 199, 58, 109, 215, 54, 54, 104, 126, 240, 39, 135, 10, 190, 57>>
      ]}
  """
  use BSV.Contract
  alias BSV.PubKey

  # this is a non swappable p2stas
  @p2stas_asm "OP_VERIFY OP_DUP OP_HASH256 OP_16 OP_SPLIT OP_15 OP_SPLIT OP_SWAP OP_14 OP_SPLIT OP_SWAP OP_13 OP_SPLIT OP_SWAP OP_12 OP_SPLIT OP_SWAP OP_11 OP_SPLIT OP_SWAP OP_10 OP_SPLIT OP_SWAP OP_9 OP_SPLIT OP_SWAP OP_8 OP_SPLIT OP_SWAP OP_7 OP_SPLIT OP_SWAP OP_6 OP_SPLIT OP_SWAP OP_5 OP_SPLIT OP_SWAP OP_4 OP_SPLIT OP_SWAP OP_3 OP_SPLIT OP_SWAP OP_2 OP_SPLIT OP_SWAP OP_1 OP_SPLIT OP_SWAP OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_SWAP OP_15 OP_SPLIT OP_SWAP OP_14 OP_SPLIT OP_SWAP OP_13 OP_SPLIT OP_SWAP OP_12 OP_SPLIT OP_SWAP OP_11 OP_SPLIT OP_SWAP OP_10 OP_SPLIT OP_SWAP OP_9 OP_SPLIT OP_SWAP OP_8 OP_SPLIT OP_SWAP OP_7 OP_SPLIT OP_SWAP OP_6 OP_SPLIT OP_SWAP OP_5 OP_SPLIT OP_SWAP OP_4 OP_SPLIT OP_SWAP OP_3 OP_SPLIT OP_SWAP OP_2 OP_SPLIT OP_SWAP OP_1 OP_SPLIT OP_SWAP OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT 00 OP_CAT OP_BIN2NUM OP_1ADD 414136d08c5ed2bf3ba048afe6dcaebafeffffffffffffffffffffffffffffff00 OP_TUCK OP_MOD OP_2DUP OP_SWAP OP_2 OP_DIV OP_GREATERTHAN OP_IF OP_SUB OP_ELSE OP_NIP OP_ENDIF OP_SIZE OP_DUP 24 OP_ADD 30 OP_SWAP OP_CAT 022079be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f8179802 OP_CAT OP_SWAP OP_CAT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_SIZE OP_DUP OP_IF OP_1SUB OP_ENDIF OP_SPLIT OP_SWAP OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT OP_CAT 41 OP_CAT 038ff83d8cf12121491609c4939dc11c4aa35503508fe432dc5a5c1905608b9218 OP_CHECKSIGVERIFY OP_4 OP_SPLIT OP_NIP 20 OP_SPLIT 20 OP_SPLIT OP_NIP 24 OP_SPLIT OP_1 OP_SPLIT OP_OVER 00 OP_CAT OP_BIN2NUM FD00 OP_GREATERTHAN OP_IF OP_4 OP_ELSE OP_2 OP_ENDIF OP_SPLIT OP_OVER 00 OP_CAT OP_BIN2NUM OP_SPLIT OP_2SWAP OP_CAT OP_ROT 17 OP_SPLIT OP_NIP OP_ROT OP_5 OP_ROLL OP_DUP OP_NOTIF OP_2ROT OP_6 OP_ROLL OP_7 OP_ROLL OP_OVER OP_IF OP_4 OP_NUM2BIN OP_CAT OP_CAT OP_ELSE OP_2DROP OP_ENDIF OP_HASH256 OP_EQUALVERIFY OP_0 OP_ELSE OP_DUP OP_1 OP_8 OP_WITHIN OP_VERIFY OP_DUP OP_1 OP_EQUAL OP_NOTIF OP_2 OP_SUB OP_6 OP_ROLL OP_3 OP_PICK OP_8 OP_ROLL OP_CAT OP_CAT OP_OVER OP_IF OP_SWAP OP_1SUB OP_SWAP OP_3 OP_PICK OP_CAT OP_7 OP_ROLL OP_CAT OP_ENDIF OP_OVER OP_IF OP_SWAP OP_1SUB OP_SWAP OP_3 OP_PICK OP_CAT OP_7 OP_ROLL OP_CAT OP_ENDIF OP_OVER OP_IF OP_SWAP OP_1SUB OP_SWAP OP_3 OP_PICK OP_CAT OP_7 OP_ROLL OP_CAT OP_ENDIF OP_OVER OP_IF OP_SWAP OP_1SUB OP_SWAP OP_3 OP_PICK OP_CAT OP_7 OP_ROLL OP_CAT OP_ENDIF OP_OVER OP_IF OP_SWAP OP_1SUB OP_SWAP OP_3 OP_PICK OP_CAT OP_7 OP_ROLL OP_CAT OP_ENDIF OP_ELSE OP_6 OP_ROLL OP_ENDIF OP_DUP OP_HASH256 OP_8 OP_ROLL OP_TUCK OP_4 OP_NUM2BIN OP_CAT OP_7 OP_ROLL OP_9 OP_ROLL OP_10 OP_ROLL OP_OVER OP_IF OP_4 OP_NUM2BIN OP_CAT OP_3DUP OP_CAT OP_CAT OP_HASH256 OP_2SWAP OP_SWAP OP_CAT OP_ELSE OP_2DROP OP_2DUP OP_CAT OP_HASH256 OP_SWAP OP_ENDIF OP_ROT OP_CAT OP_HASH256 OP_8 OP_ROLL OP_TUCK OP_EQUAL OP_DUP OP_IF OP_1 OP_ELSE OP_2 OP_ENDIF OP_SWAP OP_2SWAP OP_EQUAL OP_BOOLOR OP_VERIFY OP_3 OP_ROLL OP_NOTIF OP_DROP OP_0 OP_ENDIF OP_SWAP OP_ROT OP_4 OP_SPLIT OP_NIP OP_1 OP_SPLIT OP_OVER OP_3 OP_GREATERTHAN OP_NOT OP_VERIFY 24 OP_SPLIT OP_NIP OP_1 OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_DUP FC00 OP_GREATERTHAN OP_IF FD00 OP_GREATERTHAN OP_IF OP_4 OP_ELSE OP_2 OP_ENDIF OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_ENDIF OP_4 OP_ADD OP_SPLIT OP_NIP OP_OVER OP_1SUB OP_IF 24 OP_SPLIT OP_NIP OP_1 OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_DUP FC00 OP_GREATERTHAN OP_IF FD00 OP_GREATERTHAN OP_IF OP_4 OP_ELSE OP_2 OP_ENDIF OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_ENDIF OP_4 OP_ADD OP_SPLIT OP_NIP OP_OVER OP_2 OP_SUB OP_IF 24 OP_SPLIT OP_NIP OP_1 OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_DUP FC00 OP_GREATERTHAN OP_IF FD00 OP_GREATERTHAN OP_IF OP_4 OP_ELSE OP_2 OP_ENDIF OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_ENDIF OP_4 OP_ADD OP_SPLIT OP_NIP OP_ENDIF OP_ENDIF OP_NIP OP_1 OP_SPLIT OP_SWAP OP_2 OP_PICK OP_TUCK OP_1ADD OP_LESSTHAN OP_SWAP OP_3 OP_GREATERTHAN OP_BOOLOR OP_NOT OP_VERIFY OP_SWAP OP_DUP OP_IF OP_1SUB OP_SWAP OP_8 OP_SPLIT OP_NIP OP_1 OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_DUP FC00 OP_GREATERTHAN OP_IF FD00 OP_GREATERTHAN OP_IF OP_4 OP_ELSE OP_2 OP_ENDIF OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_ENDIF OP_SPLIT OP_NIP OP_SWAP OP_ENDIF OP_DUP OP_IF OP_1SUB OP_SWAP OP_8 OP_SPLIT OP_NIP OP_1 OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_DUP FC00 OP_GREATERTHAN OP_IF FD00 OP_GREATERTHAN OP_IF OP_4 OP_ELSE OP_2 OP_ENDIF OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_ENDIF OP_SPLIT OP_NIP OP_SWAP OP_ENDIF OP_IF OP_8 OP_SPLIT OP_NIP OP_1 OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_DUP FC00 OP_GREATERTHAN OP_IF FD00 OP_GREATERTHAN OP_IF OP_4 OP_ELSE OP_2 OP_ENDIF OP_SPLIT OP_SWAP 00 OP_CAT OP_BIN2NUM OP_ENDIF OP_SPLIT OP_NIP OP_ENDIF OP_8 OP_SPLIT OP_1 OP_SPLIT OP_OVER 00 OP_CAT OP_BIN2NUM OP_DUP FC00 OP_GREATERTHAN OP_IF FD00 OP_GREATERTHAN OP_IF OP_4 OP_ELSE OP_2 OP_ENDIF OP_SPLIT OP_OVER 00 OP_CAT OP_BIN2NUM OP_2SWAP OP_CAT OP_ROT OP_ROT OP_ENDIF OP_SPLIT OP_DROP OP_3 OP_SPLIT OP_SWAP 76a914 OP_EQUALVERIFY 14 OP_SPLIT OP_NIP OP_3 OP_PICK OP_NOTIF OP_5 OP_PICK OP_EQUALVERIFY OP_DROP OP_ELSE OP_2SWAP OP_ENDIF OP_BIN2NUM OP_DUP OP_VERIFY OP_ENDIF OP_OVER OP_0NOTEQUAL OP_IF OP_5 OP_ELSE OP_3 OP_ENDIF OP_ROLL OP_DUP 6c05 OP_SPLIT OP_NIP 14 OP_SPLIT OP_SIZE OP_IF OP_1 OP_SPLIT OP_SWAP OP_DUP OP_IF 00 OP_CAT OP_BIN2NUM OP_SPLIT OP_SWAP OP_ELSE OP_DROP OP_FALSE OP_ENDIF OP_NIP OP_ENDIF OP_TOALTSTACK OP_3 OP_PICK OP_0NOTEQUAL OP_IF OP_3 OP_PICK OP_2 OP_EQUAL OP_IF OP_4 OP_ROLL OP_TOALTSTACK OP_4 OP_ROLL OP_TOALTSTACK OP_ELSE OP_SWAP OP_TOALTSTACK OP_6 OP_ROLL OP_TOALTSTACK OP_3 OP_ROLL OP_SWAP OP_2ROT OP_SWAP OP_2ROT OP_2ROT OP_ENDIF OP_ENDIF OP_4 OP_ROLL OP_8 OP_SPLIT OP_SWAP OP_BIN2NUM OP_4 OP_ROLL OP_5 OP_PICK OP_NOTIF OP_ADD OP_ELSE OP_5 OP_PICK OP_1 OP_EQUAL OP_IF OP_SWAP OP_ENDIF OP_TOALTSTACK OP_ENDIF OP_SWAP OP_4 OP_SPLIT OP_NIP 20 OP_SPLIT OP_DROP OP_DEPTH OP_1SUB OP_ROLL OP_DUP OP_VERIFY OP_DUP OP_8 OP_NUM2BIN OP_DEPTH OP_1SUB OP_ROLL OP_DUP OP_6 OP_ROLL OP_EQUAL OP_NOTIF OP_7 OP_PICK 76a914 OP_CAT OP_SWAP OP_CAT OP_5 OP_PICK OP_ELSE 1976a914 OP_SWAP OP_CAT 88ac OP_ENDIF OP_CAT OP_CAT OP_5 OP_PICK OP_IF OP_FROMALTSTACK OP_DUP OP_VERIFY OP_DUP OP_DEPTH OP_1SUB OP_ROLL OP_NUMEQUALVERIFY OP_8 OP_NUM2BIN OP_CAT OP_FROMALTSTACK 76a914 OP_CAT OP_DEPTH OP_1SUB OP_ROLL OP_CAT OP_FROMALTSTACK OP_CAT OP_CAT OP_ELSE OP_FROMALTSTACK OP_DUP OP_TOALTSTACK OP_SIZE OP_IF OP_SIZE OP_1SUB OP_0 OP_SWAP OP_NUM2BIN OP_1 OP_CAT OP_AND OP_ENDIF OP_NOTIF OP_DEPTH OP_10 OP_GREATERTHAN OP_IF OP_SWAP OP_DEPTH OP_1SUB OP_ROLL OP_DUP OP_VERIFY OP_TUCK OP_ADD OP_ROT OP_ROT OP_8 OP_NUM2BIN OP_CAT OP_6 OP_PICK 76a914 OP_CAT OP_DEPTH OP_1SUB OP_ROLL OP_CAT OP_5 OP_PICK OP_CAT OP_CAT OP_ENDIF OP_ENDIF OP_ENDIF OP_FROMALTSTACK OP_6 OP_ROLL OP_1 OP_EQUAL OP_IF OP_DROP OP_FALSE OP_ELSE OP_SIZE OP_IF OP_SIZE OP_1SUB OP_0 OP_SWAP OP_NUM2BIN OP_1 OP_CAT OP_AND OP_ENDIF OP_ENDIF OP_NOTIF OP_DEPTH OP_9 OP_GREATERTHAN OP_IF OP_SWAP OP_DEPTH OP_1SUB OP_ROLL OP_DUP OP_VERIFY OP_TUCK OP_ADD OP_ROT OP_ROT OP_8 OP_NUM2BIN OP_CAT OP_5 OP_PICK 76a914 OP_CAT OP_DEPTH OP_1SUB OP_ROLL OP_CAT OP_5 OP_PICK OP_CAT OP_CAT OP_ENDIF OP_DEPTH OP_9 OP_GREATERTHAN OP_IF OP_SWAP OP_DEPTH OP_1SUB OP_ROLL OP_DUP OP_VERIFY OP_TUCK OP_ADD OP_ROT OP_ROT OP_8 OP_NUM2BIN OP_CAT OP_5 OP_PICK 76a914 OP_CAT OP_DEPTH OP_1SUB OP_ROLL OP_CAT OP_5 OP_PICK OP_CAT OP_CAT OP_ENDIF OP_ENDIF OP_SWAP OP_3 OP_ROLL OP_NUMEQUALVERIFY OP_4 OP_PICK OP_IF OP_5 OP_PICK OP_8 OP_NUM2BIN OP_CAT 1976a914 OP_5 OP_PICK OP_CAT 88ac OP_CAT OP_CAT OP_ENDIF OP_HASH256 OP_EQUAL OP_2SWAP OP_2DROP OP_NIP OP_NIP"

  def prefix(ctx, address) do
    ctx
    |> op_dup
    |> op_hash160
    |> push(address.pubkey_hash)
    |> op_equalverify
    |> op_checksig
  end

  def suffix(ctx, redeem_address, flags, data) do
    #OP_RETURN <"redemption address"/"protocol ID" - 20 bytes> <flags field - upto 255B length> <optional data field/s - upto around 4.2GB size>
    ctx
    |> op_return
    |> push(redeem_address.pubkey_hash)
    |> push(flags)
    |> push(data)
  end

  # def test() do
  #   {:ok, p2stas} = BSV.Script.from_asm(@p2stas_asm)
  # end

  defp asm_push(op_or_data, ctx) when is_atom(op_or_data) do
    Contract.script_push(ctx, op_or_data)
  end

  defp asm_push(op_or_data, ctx) when is_binary(op_or_data) do
    push(ctx, op_or_data)
  end

  def p2stas(ctx) do
    p2stas = BSV.Script.from_asm!(@p2stas_asm)
    Enum.reduce(Map.get(p2stas, :chunks), ctx, &asm_push/2)
  end

  @impl true
  def locking_script(ctx, %{address: address, redeem_address: redeem_address, flags: flags, data: data}) do
    ctx
    |> prefix(address)
    |> p2stas()
    |> suffix(redeem_address, flags, data)
  end

  @impl true
  def unlocking_script(ctx, %{keypair: keypair}) do
    ctx
    |> sig(keypair.privkey)
    |> push(PubKey.to_binary(keypair.pubkey))
  end

end
